# -x assembler-with-cpp
# gpSP makefile
# Gilead Kutnick - Exophase

# Global definitions

VERSION_MAJOR = 3
VERSION_MINOR = 2
VERSION_BUILD = 07
# コンパイル条件の設定

USER_MODE = 1

# 拡張メモリの使用のON/OFF
M64_MODE = 1

# バージョン表記にtestとBUILD番号を含めるかどうかの設定
TEST_MODE = 1

# CコアによるCPUエミュレーションのON/OFF
C_CORE_MODE = 0

# WLANのON/OFF
ADHOC_MODE = 1

