# -x assembler-with-cpp
# gpSP makefile
# Gilead Kutnick - Exophase

# Global definitions

USER_MODE = 1
M64_MODE = 1
VERSION_MAJOR = 3
VERSION_MINOR = 2
VERSION_BUILD = 03
TEST_MODE = 1
#ADHOC_MODE = 1

include Makefile.in

